apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: load-generator
  name: load-generator
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: load-generator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
        - image: busybox:1.28
          imagePullPolicy: IfNotPresent
          name: busybox
          args:
          - /bin/sh
          - -c
          - while sleep 0.01; do wget -q -O- http://my-app; done
